---
title: "About"
---

About me


  I am from Colorado, a headwater state often the center of water conflicts, resulting in my interest in water. Water is a resource able to connect every living thing, but it also has the power to divide. This is part of the reason I chose to study Watershed Science and Sustainability at Colorado State. When I first entered school, I was unsure of what I wanted to do, but I was naturally drawn to this major because of my love and interest in water. I am passionate about understanding and managing water resources, especially in ways that promote sustainability and equity. With a minor in Statistics and Global Environmental Sustainability, I aim to combine scientific analysis with sustainable practices to address unique challenges. My ambitions lie in working with municipalities to manage resources effectively, taking into account both environmental concerns and community needs, especially as water scarcity and quality issues persist in the West. 


  Through my coursework and field studies, I have developed a strong foundation in watershed topics including hydrology, water quality, water law and policy, and statistical analysis. Water quality tools I have experience with include Secchi disks, Van Dorn samplers, Sondes, and plankton nets. Additionally, I have worked measuring streamflow with cross-sectional surveys utilizing tools such as pygmy current meters. Using data gathered from these tools, I have assessed watershed characteristics such as trophic state with the assistance of R programming and Excel for data analysis and visualization. This has strengthened my ability to collect and interpret environmental data.


