---
title: "Projects"
format: html
---

##  Snow Hydrology

*Data from ASOS station 0CO, Berthoud Pass*

[map](media/lc_map.png)

```{r, include=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(ggplot2)
library(viridis)
library(stringr)

ASOS<-read.csv("data/0CO_works copy.csv")


ASOS <- ASOS %>%
  mutate(wind_speed_ms = as.numeric(sknt) * 0.514)%>%
  mutate(valid = mdy(valid))


windassign <- ASOS %>%
  mutate(month = month(valid)) %>%
  group_by(month) %>%
  summarise(
    avg_wind = mean(wind_speed_ms, na.rm = TRUE),
    max_wind = max(wind_speed_ms, na.rm = TRUE)
  )
  

windassign <- ASOS %>%
  mutate(
    month_date = floor_date(valid, "month"),                 
    month_lab = month(valid, label = TRUE, abbr = TRUE)
  ) %>%
  group_by(month_date, month_lab) %>%
  summarise(
    avg_wind = mean(wind_speed_ms, na.rm = TRUE),
    max_wind = max(wind_speed_ms, na.rm = TRUE),
    .groups = "drop"
  )

sy_months <- c("Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug")

windassign <- windassign %>%
  mutate(month_lab = factor(month_lab, levels = sy_months))



```


**Temperature: monthly maximum, average, minimum in degrees C **

```{r, echo=FALSE,message=FALSE,warning=FALSE}




precip.temp<-read.csv("data/0CO_Precip&Temp copy.csv")

 precip.temp<-precip.temp%>%
   mutate(as.numeric(Temp_avg_C))%>%
  mutate( Month = factor(Month,
      levels = c("Sep", "Oct", "Nov", "Dec", 
                 "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug")))
ggplot(precip.temp, aes(x = Month)) +
  geom_line(aes(y = Max_temp_C, color = "Maximum",group = 1,alpha = .5), size = 1) +
  geom_line(aes(y = Temp_avg_C, color = "Average",group = 1,alpha = .5), size = 1) +
  geom_line(aes(y = Min_Temp_C, color = "Minimum",group=1,alpha = .5), size = 1) +
  geom_point(aes(y = Max_temp_C, color = "Maximum"),size=2) +
  geom_point(aes(y = Temp_avg_C, color = "Average"),size=2) +
  geom_point(aes(y = Min_Temp_C, color = "Minimum"),size=2) +
  labs(
    x = "Month",
    y = "Temperature (°C)",
    caption = "Figure 2. Monthly average, maximum, and minimum temperature (in °C) for snow year 2024 at ASOS station 0CO – 
Berthoud Pass. Data sourced from NCDC "
  ) +
  theme_bw() + theme(plot.caption = element_text(hjust = 0,size = 12))+
  scale_color_manual(
    name = "Temperature Type",
    values = c("Maximum" = "firebrick3", "Average" = "grey3", "Minimum" = "cyan4"))+guides(alpha="none")
  

```


**Precipitation:monthly totals mm**


```{r, echo=FALSE}


ggplot(precip.temp)+geom_col(aes(x=Month,y=Precip_mm),fill="dodgerblue4",color="black",width = 0.8) + labs(x="Month", y="Precipitation (mm)", caption = "Figure 1. Monthly total precipitation (in millimeters) for snow year 2024 (September 2023 to August 2024) at ASOS 
station 0CO - Berthoud Pass. Data sourced from NCDC.") + theme_bw()+theme(panel.grid.major = element_line(color = "grey69"),plot.caption = element_text( hjust = 0),panel.grid.major.x = element_blank(),panel.grid.minor= element_line(color = "grey69"))



```


**Wind Rose**


```{r, echo=FALSE,message=FALSE,warning=FALSE}
wind_direct <- ASOS %>%
  mutate(
    wind_type = case_when(
      drct == 0 ~ "Calm",
      drct == "VRB" ~ "Variable",
      TRUE ~ "Directional"
    ), sector = ifelse(wind_type == "Directional",
                    floor((as.numeric(drct) + 5) / 10) * 10, NA) 
  )%>%filter(!is.na(drct))



wind_freq <- wind_direct %>%
  group_by(sector, wind_type) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(percent = n / sum(n) * 100) %>%
  filter(wind_type == "Directional") %>%
  filter(!is.na(sector))


max_pct <- ceiling(max(wind_freq$percent))

ggplot(wind_freq, aes(x = factor(sector), y = percent, fill = percent)) +
  geom_bar(stat = "identity", color = "black", size = 0.1) +
  coord_polar(start = pi/36) +
  scale_fill_viridis_c(option = "C", name = "Frequency (%)") +
  labs(
    x = "Wind Direction (°)",
    y = NULL,
    caption = "Figure 5. Wind rose direction at ASOS station 0CO – Berthoud Pass for snow year 2024. Data sourced from NCDC. Rose 
split into 36 sectors where 360° is north. A wind direction of 0 is no wind so it has been extracted from this graph. 0 appeared 
in the snow year 52 times in hourly data.There is also 435 missing wind entries from this data and no variable (VRB) wind."

  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_blank(),axis.ticks.y = element_blank()
  )+theme(
    axis.text.y = element_blank(),
    plot.caption = element_text(vjust = -0.5,hjust = 0.25))
```

## [name](filepath)

